# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/winter/test/models/channel/columns.yaml

# Model Class name
modelClass: Winter\Test\Models\Channel

# List Title
title: winter.test::lang.models.channel.label_plural

# Link URL for each record
recordUrl: winter/test/channels/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Show tree
showTree: true
treeExpanded: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_channels_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
