# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: ~/plugins/winter/test/models/post/columns.yaml

# Model Class name
modelClass: Winter\Test\Models\Post

# List Title
title: Manage Posts

# Link URL for each record
recordUrl: winter/test/posts/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc

# Display checkboxes next to each record
# showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_posts_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt

filter:
    scopes:
        show_deleted:
            label: Show deleted
            type: checkbox
            modelClass: Winter\Test\Models\Post
            scope: withTrashed
            default: 0

