# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: winter.test::lang.models.country.label

# Model Form Field configuration
form: ~/plugins/winter/test/models/country/fields.yaml

# Model Class name
modelClass: Winter\Test\Models\Country

# Default redirect location
defaultRedirect: winter/test/countries

# Create page
create:
    title: Create Country
    redirect: winter/test/countries/update/:id
    redirectClose: winter/test/countries

# Update page
update:
    title: Edit Country
    redirect: winter/test/countries
    redirectClose: winter/test/countries

# Preview page
preview:
    title: Preview Country
