# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: ~/plugins/winter/test/models/person/columns.yaml

# Model Class name
modelClass: Winter\Test\Models\Person

# List Title
title: winter.test::lang.models.person.label_plural

# Link URL for each record
recordUrl: winter/test/people/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 2

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc

# Display checkboxes next to each record
# showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
        mode: any

filter: config_filter.yaml
